workspace: 'scidev/testing'
compute-env: 'seqera_aws_ireland_fusionv2_nvme_benchmark_testing'
profile: 'test'
pipelines:
  rnaseq: 3.12.0
  scrnaseq: 2.3.1
  smrnaseq: 2.2.1
  demultiplex: 1.3.0
  hic: 2.1.0
outdir_base: 's3://scidev-eu-west-1/benchmark_tests'
config_file: 'custom.config'
