# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
## general purpose linting and formatting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
## Python specific linting and formatting
repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
    - repo: https://github.com/pycqa/pydocstyle
      rev: 4.0.0  # pick a git hash / tag to point to
      hooks:
        - id: pydocstyle
    - repo: https://github.com/pylint-dev/pylint
      rev: v2.17.3
      hooks:
        - id: pylint
    - repo: https://github.com/PyCQA/flake8
      rev: c8d75d9
      hooks:
        - id: flake8