pipelines:
  - name: "nf-core-rnaseq"
    url: "https://github.com/nf-core/rnaseq"
    description: "RNA sequencing analysis pipeline using STAR, RSEM, HISAT2 or Salmon with gene/isoform counts and extensive quality control."
    workspace: "seqeralabs/showcase"
    compute-envs: "seqera_aws_ireland_fusionv2_nvme"
    revision: "3.12.0"
    profile: "test"
    labels: ["star_salmon", "yeast"]
    pre-run: "./pre-run.sh"
    params:
      outdir: "s3://seqeralabs-showcase/nf-core-rnaseq/results"
    overwrite: False
  - name: "nf-core-rnaseq-human"
    url: "https://github.com/nf-core/rnaseq"
    description: "RNA sequencing analysis pipeline using STAR, RSEM, HISAT2 or Salmon with gene/isoform counts and extensive quality control."
    workspace: "seqeralabs/showcase"
    compute-envs: "seqera_aws_ireland_fusionv2_nvme"
    revision: "3.12.0"
    labels: ["GRCh37", "star_salmon", "human"]
    pre-run: "./pre-run.sh"
    params:
      outdir: "s3://seqeralabs-showcase/nf-core-rnaseq-human/results"
      genome: "GRCh37"
    overwrite: False
